**Генерация OLAP-куба, где зафиксированы продажи товаров в розничной сети по городам.**

**Оси:**
 - 0: ID товара
 - 1: ID города
 - 2: день месяца, в котором осуществляются продажи
 
 - ***0: ID товара - 3(ластик, линейка, карандаш)***
 - ***1: ID города - 2(Санкт-Петербург, Москва)***
 - ***2: день месяца, в котором осуществляются продажи - 7(Дни недели)***
 

In [1]:
import numpy as np

In [2]:
a = 100*np.random.random((3,2,7))
a

array([[[44.48526504, 27.93789001, 27.69594153, 32.73020598,
          9.42971657,  4.40100041, 85.38028851],
        [34.14516879, 97.10771038, 63.8554813 , 20.79193136,
          8.57681228, 64.19031847, 41.01751661]],

       [[48.75783553, 56.73061979, 55.03463315, 30.77496323,
         34.9955855 , 86.71385683, 97.63069512],
        [33.71238557, 34.34623991, 53.25276884, 70.09950325,
         10.34527785, 45.57679723, 26.64710982]],

       [[92.57419044, 53.4979941 , 92.75737281, 88.11172001,
         58.84635432, 71.08512718,  8.86736303],
        [ 8.06448017, 16.80081517, 27.13769018, 15.68362656,
         48.91868596, 10.75206254, 26.16249147]]])

In [3]:
a = a.astype(int)
a

array([[[44, 27, 27, 32,  9,  4, 85],
        [34, 97, 63, 20,  8, 64, 41]],

       [[48, 56, 55, 30, 34, 86, 97],
        [33, 34, 53, 70, 10, 45, 26]],

       [[92, 53, 92, 88, 58, 71,  8],
        [ 8, 16, 27, 15, 48, 10, 26]]])

### Анализ

In [4]:
a0articul = a[:,:,:]
a0articul

array([[[44, 27, 27, 32,  9,  4, 85],
        [34, 97, 63, 20,  8, 64, 41]],

       [[48, 56, 55, 30, 34, 86, 97],
        [33, 34, 53, 70, 10, 45, 26]],

       [[92, 53, 92, 88, 58, 71,  8],
        [ 8, 16, 27, 15, 48, 10, 26]]])

**Информация по Санкт-Петербургу**

In [5]:
a1piter = a[:,0,:]
a1piter

array([[44, 27, 27, 32,  9,  4, 85],
       [48, 56, 55, 30, 34, 86, 97],
       [92, 53, 92, 88, 58, 71,  8]])

**Информация за выходные в городах вместе**

In [6]:
a2weekend = a[:,:,5] +  a[:,:,6] 
a2weekend

array([[ 89, 105],
       [183,  71],
       [ 79,  36]])

**Сделали срез: **
 - товары(ластик, карандаш), 
 - Санкт-Петербург Москва, 
 - в выходные.

In [7]:
a2weekend = a[(0,2),:,5:7]
a2weekend 

array([[[ 4, 85],
        [64, 41]],

       [[71,  8],
        [10, 26]]])

**суммировали ластики и карандаши по дням в Санкт-Петербурге и Москве**

In [8]:
a2weekend.sum(axis=1)

array([[ 68, 126],
       [ 81,  34]])

**суммировали **
 - за два выходных 
 - все ластики 
 - в Санкт-Петербурге и Москве, 
 - и все карандаши в Санкт-Петербурге и Москве

In [9]:
a2weekend.sum(axis=2)

array([[ 89, 105],
       [ 79,  36]])

**Для получившегося OLAP-куба считаем** 
 - суммарные, 
 - средние, 
 - минимальные 
 - и максимальные продажи,
 
**зафиксировав значения по одной, двум или трём осям:**

In [10]:
a2weekend.sum()

309

In [11]:
a2weekend.mean()

38.625

In [12]:
a2weekend.min()

4

In [13]:
a2weekend.max()

85

**средние продажи **
 - в субботу и воскресенье 
 - в Санкт-Петербурге и Москве 
 - по товарам ластик и карандаш

In [14]:
a2weekend.mean(axis = 0)

array([[37.5, 46.5],
       [37. , 33.5]])

**за выходные больше в Санкт-Петербурге или Москве**

In [15]:
a2weekend.sum(axis = 2)

array([[ 89, 105],
       [ 79,  36]])

In [16]:
a2weekend.sum(axis = 2).min(axis = 0)

array([79, 36])

### Срез: за будни все товары по всем городам

In [17]:
workindays = a[:,:,0:5]
workindays

array([[[44, 27, 27, 32,  9],
        [34, 97, 63, 20,  8]],

       [[48, 56, 55, 30, 34],
        [33, 34, 53, 70, 10]],

       [[92, 53, 92, 88, 58],
        [ 8, 16, 27, 15, 48]]])

**Анализ среза**

In [18]:
workindays.sum()

1281

In [19]:
workindays.min()

8

In [20]:
workindays.max()

97

In [21]:
workindays.mean()

42.7

In [22]:
# сумма по дням, по axis= 2
workindays.sum(axis= 2)

array([[139, 222],
       [223, 200],
       [383, 114]])

### Конец анализа среза: будние дни

In [23]:
a0articul.sum(axis = 1)

array([[ 78, 124,  90,  52,  17,  68, 126],
       [ 81,  90, 108, 100,  44, 131, 123],
       [100,  69, 119, 103, 106,  81,  34]])

In [24]:
# сумма по 0 артикулу товара
a.sum( axis = 1 )

array([[ 78, 124,  90,  52,  17,  68, 126],
       [ 81,  90, 108, 100,  44, 131, 123],
       [100,  69, 119, 103, 106,  81,  34]])

In [25]:
a0 = a[0,0,:]
a0

array([44, 27, 27, 32,  9,  4, 85])

In [26]:
# сумма по 0 артикулу товара , 0 магаз, 0 день
a.sum( axis = 1 )[0,1]

124

In [27]:
# сумма по 0 артикулу товара , 0 день в 0 городе и 1 городе
a.sum( axis = 1 )[0,:]

array([ 78, 124,  90,  52,  17,  68, 126])

In [28]:
#инфа по ластику
a[ 0, :]

array([[44, 27, 27, 32,  9,  4, 85],
       [34, 97, 63, 20,  8, 64, 41]])

In [29]:
a.min(axis=1)

array([[34, 27, 27, 20,  8,  4, 41],
       [33, 34, 53, 30, 10, 45, 26],
       [ 8, 16, 27, 15, 48, 10,  8]])

In [30]:
a.sum(axis = 2) 

array([[228, 327],
       [406, 271],
       [462, 150]])

In [31]:
m = a.mean(axis = 1) 
m

array([[39. , 62. , 45. , 26. ,  8.5, 34. , 63. ],
       [40.5, 45. , 54. , 50. , 22. , 65.5, 61.5],
       [50. , 34.5, 59.5, 51.5, 53. , 40.5, 17. ]])

In [32]:
m.sum(axis = 0)

array([129.5, 141.5, 158.5, 127.5,  83.5, 140. , 141.5])

In [33]:
#среднее по товару
n = a.sum(axis = 0).astype(int)
n


array([[184, 136, 174, 150, 101, 161, 190],
       [ 75, 147, 143, 105,  66, 119,  93]])

In [34]:
# сумму по городам
n.sum(axis = 1) 

array([1096,  748])